name: Deploy SmartBurguerValue API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITHUB_ACTIONS_KEY }}

      - name: Deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no deploy@189.126.105.76 << 'EOF'
          echo "üîÑ Atualizando reposit√≥rio..."
          cd ~/SmartBurguerValue || exit
          git fetch --all
          git reset --hard origin/main

          echo "‚öôÔ∏è Publicando API..."
          cd src/SmartBurguerValueAPI
          dotnet publish -c Release -o ~/app

          echo "‚úÖ Deploy conclu√≠do com sucesso!"
          EOF
